services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    # network_mode: 'host'
    network_mode: 'bridge'
    ports:
      - 8096:8096
    volumes:
      - ~/Documents/Docker/jellyfin/config:/config:z
      - ~/Documents/Docker/jellyfin/cache:/cache:z  
      - type: bind
        source: /mnt/mydrive/Media
        target: /media

      # - type: bind
      #   source: /path/to/media2
      #   target: /media2
      #   read_only: true
      
      # Optional - extra fonts to be used during transcoding with subtitle burn-in
      # - type: bind
      #   source: /path/to/fonts
      #   target: /usr/local/share/fonts/custom
      #   read_only: true
    restart: 'unless-stopped'
    environment:
      - TZ=America/Phoenix
      # Optional - alternative address used for autodiscovery
      # - JELLYFIN_PublishedServerUrl=http://example.com
    extra_hosts:
      # Optional - may be necessary for docker healthcheck to pass if running in host network mode
      - 'host.docker.internal:host-gateway'

# volumes:
#   config:
#   cache: